#!bin/bash

brew install --cask firefox

brew install --cask google-chrome

brew install --cask iterm2

brew install --cask raycast

brew install --cask karabiner-elements

brew install --cask android-studio

brew install --cask intellij-idea-ce

brew install --cask visual-studio-code

brew install --cask bitwarden

brew install --cask keka

brew install --cask iina

brew install --cask tableplus

brew install --cask proxyman

brew install --cask folx

brew install --cask kap

brew install --cask appcleaner

brew install --cask spotify

brew install --cask disk-inventory-x

brew install --cask imageoptim

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Additional things to do:'
echo ' 1. Load configs for IDEs and iTerm2 from /configs'