#!/bin/bash

function bootstrap() {
    sudo -v
    source ~/.dotfiles/install
}

echo 'Bootstrap terminal and install applications'
echo '------------------'
echo 'This will reset your terminal. Are you sure you want to do this? (y/n)'
read -p 'Answer: ' reply

if [[ $reply =~ ^[Yy]$  ]]; then
    bootstrap
fi