#!/bin/bash

echo 'Bootstrap your Mac'

while true
do
    echo '-----------------'
    echo 'Choose an option:'
    echo ' 1. Bootstrap terminal'
    echo ' 2. Install applications'
    echo ' 3. Set system defaults (macOS)'
    echo ' 0. Exit'
    read -p 'Answer: ' reply

    case $reply in
        1)
            sudo -v
            source $HOME/.dotfiles/terminal
            ;;
        2)
            source $HOME/.dotfiles/apps
            ;;
        3)
            sudo -v
            source $HOME/.dotfiles/defaults
            ;;
        0)
            break
            ;;
        *)
            echo 'Unknown option. Try again'
            ;;
    esac
done
