#!bin/bash

# Hide the "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install oh-my-zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

# Install Homebrew and some packages
echo 'Install homebrew'
echo '----------------'
sudo rm -rf /opt/homebrew/Cellar /usr/local/Cellar && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

echo 'Install git'
echo '-----------'
brew install git

echo 'Install pyenv'
echo '-------------'
brew install pyenv

echo 'Install docker'
echo '--------------'
brew install docker

echo 'Install php'
echo '-----------'
brew install php

echo 'Install composer'
echo '----------------'
brew install composer

echo 'Install node'
echo '------------'
brew install node

echo 'Install mysql'
echo '-------------'
brew install mysql
brew services start mysql

echo 'Install wget'
echo '------------'
brew install wget

echo 'Install tree'
echo '-----------'
brew install tree

echo 'Install trash'
echo '-------------'
brew install trash

# Install some applications as casks
echo 'Install firefox'
echo '---------------'
brew install --cask firefox

echo 'Install google-chrome'
echo '---------------------'
brew install --cask google-chrome

echo 'Install rectangle'
echo '-----------------'
brew install --cask rectangle

echo 'Install linearmouse'
echo '-------------------'
brew install --cask linearmouse

echo 'Install iterm2'
echo '--------------'
brew install --cask iterm2

echo 'Install alfred'
echo '--------------'
brew install --cask alfred

echo 'Install android-studio'
echo '----------------------'
brew install --cask android-studio

echo 'Install intellij-idea'
echo '---------------------'
brew install --cask intellij-idea

echo 'Install visual-studio-code'
echo '--------------------------'
brew install --cask visual-studio-code

echo 'Install bitwarden'
echo '-----------------'
brew install --cask bitwarden

echo 'Install keka'
echo '------------'
brew install --cask keka

echo 'Install iina'
echo '------------'
brew install --cask iina

echo 'Install tableplus'
echo '-----------------'
brew install --cask tableplus

echo 'Install folx'
echo '------------'
brew install --cask folx

echo 'Install postman'
echo '---------------'
brew install --cask postman

echo 'Install kap'
echo '-----------'
brew install --cask kap

echo 'Install appcleaner'
echo '------------------'
brew install --cask appcleaner

echo 'Install spotify'
echo '---------------'
brew install --cask spotify

echo 'Install calibre'
echo '---------------'
brew install --cask calibre

echo 'Install disk-inventory-x'
echo '------------------------'
brew install --cask disk-inventory-x

echo 'Install imageoptim'
echo '------------------'
brew install --cask imageoptim

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Additional things to do:'
echo '1. Set some sensible OSX defaults by running: $HOME/.dotfiles/macos/set-defaults.sh.'
echo '2. Install pyenv latest version by running pyenv install 3:latest and then pyenv global _version_.'
echo '3. Install remaining applications listed in the apps.md.'
echo '4. Load configs for IDEs and iTerm2 from /configs.'