#!/bin/bash

# Hide the "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink git config
rm $HOME/.gitconfig
ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig

# Symlink git ignore
rm $HOME/.gitignore
ln -s $HOME/.dotfiles/shell/.gitignore $HOME/.gitignore

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc

# Symlink nvim prefs
rm $HOME/.config/nvim
ln -s $HOME/.dotfiles/shell/nvim $HOME/.config

# Symlink IdeaVim prefs
rm $HOME/.ideavimrc
ln -s $HOME/.dotfiles/configs/.ideavimrc $HOME/.ideavimrc

# Symlink Karabiner config
rm $HOME/.config/karabiner
ln -s $HOME/.dotfiles/configs/karabiner $HOME/.config

# Symlink global fd ignore file
rm $HOME/.config/fd/ignore
mkdir -p $HOME/.config/fd/
ln -s $HOME/.dotfiles/configs/.fdignore $HOME/.config/fd/ignore

# Symlink p10k config
rm $HOME/.p10k.zsh
ln -s $HOME/.dotfiles/shell/.p10k.zsh $HOME/.p10k.zsh

# Symlink iTerm2 shell integration script
rm $HOME/.iterm2_shell_integration.zsh
ln -s $HOME/.dotfiles/shell/.iterm2_shell_integration.zsh $HOME/.iterm2_shell_integration.zsh

# Install Homebrew and some packages
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

eval "$(/opt/homebrew/bin/brew shellenv)"

brew install git

# Clone zsh-autosuggestions and zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Clone Powerlevel10k theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Install nvm
git clone https://github.com/lukechilds/zsh-nvm.git $HOME/.zsh-nvm

brew install pyenv

brew install rbenv

brew install java
sudo ln -sfn $(brew --prefix)/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

brew install docker

brew install php

brew install composer

brew install mysql
brew services start mysql

brew install wget

brew install tree

brew install trash

brew install imagemagick

brew install fzf

brew install bat

brew install ripgrep

brew install fd

brew install jq

brew install gh

brew install gradle

brew install hugo

brew install mailhog

brew install neovim

brew install btop

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Additional things to do:'
echo ' 1. Install pyenv latest version by running pyenv install _version_ and then pyenv global _version_'
echo ' 2. Install rbenv latest version by running rbenv install _version_ and then rbenv global _version_'
echo ' 3. Install nvm latest version by running nvm install node'
